### ISSUE TITLE
Make Treemap colors less saturated or add an option to adjust colors

### ISSUE THREAD

**Issue by RollingTL** [btd/rollup-plugin-visualizer#107]
Full page of red is very painful for eyes:

![Screen Shot 2021-12-18 at 18 31 27](https://user-images.githubusercontent.com/16714526/146642646-08413ed4-1f96-473e-8ccd-a68ddccad33f.png)

Such saturated red is hard to work with especially in dark room. It hurts. I personally feel bad color impact more than twenty minutes after I closed my Stat.html.

One minor thing - in some places red is rather dark and still has black text on which is hard to read and cause unpleasant feeling due to lack of contrast.

I think other colors - vivid pink, vivid yellow, vivid green -  hurt eyes too and are better to change, but those I didn't see as my project rendered in red only. I only can imagine what a pain to look at full page of vivid pink.

It would be better to select more calm and desaturated colors:

![3](https://user-images.githubusercontent.com/16714526/146642716-6fea3ed0-ff6c-45a0-985f-5ec6eea19d23.png)

May be its better to add an option for user to select color by himself.

On the contrary current 'sunburst' and 'network' color schemes are more eye friendly.

**Comment by btd** [comment]
You over simplified the problem. I guarantee it is much more complex then just one unpleasant color. I open for discussion, and you want to contribute something colors for tree map is here https://github.com/btd/rollup-plugin-visualizer/blob/master/src/treemap/color.ts if you will find more adjusted settings feel free to post screenshot.
Also keep in mind that is not one color, but every bundle has own color. So asking user to select finite number of colors is not the option that i will ever consider - it just will never work.
About text color, i use 2 colors: black and white, which one is choosed by relative luminance https://www.w3.org/TR/WCAG20/#relativeluminancedef if you can suggest i am open again

**Comment by RollingTL** [comment]
I see now that it is not that simple. And asking user to select color is not applicable.
In fact I tried to read code but this is too complicated. I do not fully understand the logic in **color.ts** but the bigger problem is that I don't even know how to run modified code to see results.

May be it is better to decrease only saturation and keep all other logic intact. 
If you simply programmatically decrease every color saturation I think it will be more user friendly. 

Something like that:

![6](https://user-images.githubusercontent.com/16714526/146650432-7ebf9a21-0fda-41f6-9147-4691a4d9ba56.png)

**Comment by btd** [comment]
As i said it is not that simple. But there is not so much constants responsible for color. I will not have time to look on this at least till the end for January. If you want to try to play with constants i can explain how and where. It is only few places.

**Comment by btd** [comment]
I reduced saturation for treemap
<img width="1410" alt="Screenshot 2022-01-15 at 12 05 47" src="https://user-images.githubusercontent.com/334851/149619441-75084a48-a6b8-49cd-8684-96fb03f85cdb.png">
