### ISSUE TITLE
It's toke several minutes to render content in chrome

### ISSUE THREAD

**Issue by Enoooch** [btd/rollup-plugin-visualizer#108]
The stats page just keep loading, but it's render instantly in firefox and safari.

Node v16.13.0
MacOS 12.1
Chrome version 96.0.4664.110 (Official Build) (arm64)

![image](https://user-images.githubusercontent.com/39915133/147177054-ff889112-eca5-481f-a0e4-2497bf4cbf1b.png)

**Comment by btd** [comment]
I need your stats file. I cannot guess by description. Next time follow template for bug reporting

**Comment by Siger2014** [comment]
I have this problem yet
my config like this:

```javascript
visualizer({
      filename: './node_modules/.cache/visualizer/stats.html',
      open: true,
      gzipSize: true,
      brotliSize: true,
})
```
when build success open the stats.html network status is pending
stats.txt is my report html
[stats.txt](https://github.com/btd/rollup-plugin-visualizer/files/7786776/stats.txt)

**Comment by btd** [comment]
Thanks for providing me stats html. I tried several versions of chrome/chromium, and it is definitely bug in chrome.
1) chromium 98 it stuck
2) chromium 97 it works
3) chrome 96 it stuck
4) chromium 90 it works
5) chromium 88 it works
6) chromium 80 it works

I will not add any sort of fixes to workaround chrome bugs. I reported issue to chrome.
I will rest this issue open and pin it to make sure it is visible to everyone

**Comment by 33YANG** [comment]
same stats.html loading problem in chrome 96

**Comment by btd** [comment]
@33YANG yes, it is still there
you can track progress there https://bugs.chromium.org/p/chromium/issues/detail?id=1285666&q=component%3ABlink%3ESVG&can=2
But please do not spam them, i already reported everything that is necessary for them to reproduce the problem

**Comment by littlepoolshark** [comment]
Same issue here. 
chrome 97.0.4692.71
window 10

**Comment by btd** [comment]
I am closing this as chrome team fixed issue. If i am not mistaken it will be in version 98
