### ISSUE TITLE
Specify output path

### ISSUE THREAD

**Issue by Enoooch** [btd/rollup-plugin-visualizer#109]
Current param `filename` also includes file path like this `visualizer({ filename: '.test/stats.html' })`.

Don't know if add a param `outputPath` or rename to `filePath` would be more appropriate.

**Comment by btd** [comment]
While i agree that this option has poor naming, there is a [documentation](https://github.com/btd/rollup-plugin-visualizer#options) describing every option. Renaming it or adding a warning does not really improve UX, as after you make plugin works you normally do not touch it. I do not want to introduce additional noise in build process for developers.
