### ISSUE TITLE
Question: Does this match `--webpack-stats-json` output?

### ISSUE THREAD

**Issue by IanVS** [btd/rollup-plugin-visualizer#111]
There's a tool that I want to use which requires the output of webpack's stats, but I'm using rollup.  This plugin seems like it does roughly the same thing as the webpack option, so I was wondering if the format matches.  And if not, whether that's something that might be possible to do, and whether you'd consider it.  Thanks!

**Comment by btd** [comment]
Hi,
no format is not matched, they are not related to each other. I added to stats json in this plugin necessary peaces to render charts. Honestly i do not see any good reason to match webpack format it will only limit me what i can use and add. I will need to maintain and watch out for compatibility issues which i do not want and do not have time.

**Comment by IanVS** [comment]
OK, thanks for the quick response!
