### ISSUE TITLE
Is it possible to install it on a new SvelteKit project?

### ISSUE THREAD

**Issue by frederikhors** [btd/rollup-plugin-visualizer#112]
Is it possible to install it on a new [SvelteKit](https://kit.svelte.dev/) project?

**Comment by btd** [comment]
I think so. SvelteKit is using vite for build. So you need https://vitejs.dev/config/#build-rollupoptions it should looks something like this in your vite.config.js:
```js
const { visualizer } = require('rollup-plugin-visualizer');

module.exports = {
  build: {
    rollupOptions: {
      plugins: [
        visualizer()
      ]
    }
  }
}
```
Let me know if it works, i know it works with vite

**Comment by btd** [comment]
I actually just checked, it is more simple:
```js
const { visualizer } = require('rollup-plugin-visualizer');

/**
 * @returns {import('vite').UserConfig}
 */
module.exports = ({ mode }) => {
  return {
    plugins: [
      mode === 'production' &&
        visualizer({ filename: `${OUTPUT_DIR}/bundles.html`, gzipSize: true, brotliSize: true }),
    ],
  };
};
```

**Comment by frederikhors** [comment]
It doesn't work. If I'm using `service-worker.ts` in SvelteKit the only treemap I have is for that .js. Not for the `build/_app/chunks` dir.

Can you please re-open until we understand how to fix it?

And another issue we have is to not understand what changes using or not the `sourcemap` option.

**Comment by btd** [comment]
Yep, sure. Can you make me repro case?

**Comment by frederikhors** [comment]
I cannot right now but I'm using a simple new app `npm init svelte@next my-app`.

If you try building with or without sourcemaps the results are very different.

And if you create a `service-worker.ts` in root (https://kit.svelte.dev/docs/service-workers) when you build it will analyze only the `build/service-worker.js`.

**Comment by btd** [comment]
> If you try building with or without sourcemaps the results are very different.

Yes it is. It is described in readme

> And if you create a service-worker.ts in root (https://kit.svelte.dev/docs/service-workers) when you build it will analyze only the build/service-worker.js.

Well it is not actually. You can see in logs it actually executes vite 3 times, so every time file is overriden. I think i need to add option for plugin to accept function that return option based on rollup output options

**Comment by btd** [comment]
I added snippet to readme about usage with sveltekit. I tested it locally on demo app.
