### ISSUE TITLE
Include in README.md what the plugin generates

### ISSUE THREAD

**Issue by elibroftw** [btd/rollup-plugin-visualizer#114]
Usage says just to add the plugin to config, but should also include what happens after `build`. Namely that `stats.html` is generated.

**Comment by btd** [comment]
In Options `filename` it says filename that will be generate. If you want more description PR welcome

**Comment by inspire22** [comment]
Thanks! I couldn't figure out how to get the results of this plugin running, which when used as a vite plugin was in public/vite/stats.html
