### ISSUE TITLE
`visualize()` returns wrong type when loading from `vite` in TypeScript.

### ISSUE THREAD

**Issue by ennioVisco** [btd/rollup-plugin-visualizer#127]
## OS & Node info
------------------------------
- Operating System: `Darwin` (Mac OS)
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- Runtime Modules:  `unplugin-icons/nuxt`, `@vueuse/nuxt@9.2.0`, `@intlify/nuxt3@0.2.4`
- Build Modules:    `-`
------------------------------

## Screenshot of the problem
![image](https://user-images.githubusercontent.com/740025/190181121-a309f2a4-f2da-484e-ac33-53c8ea4edbf4.png)

I guess this is missing the Rollup config, which I'm not sure how to extract from nuxt, but I guess I can work on it if found helpful.

**Comment by btd** [comment]
Hi. Thanks for report. Need some details. There was similar issue recently.
Can you please run `yarn ls rollup` and `yarn ls rollup-plugin-visualizer`. I do not remember if yarn has ls command, if not try with npm pls.

**Comment by ennioVisco** [comment]
Hello, thanks @btd for the quick reply! Here are the reports:

`npm ls rollup`:
![image](https://user-images.githubusercontent.com/740025/190331171-c29868ed-2b22-4443-b098-98afe8a6228b.png)

`npm ls rollup-plugin-visualizer`:
![image](https://user-images.githubusercontent.com/740025/190331349-5a91f23e-7adb-42ee-add5-7eabcd09fe03.png)

@n4o847 It doesn't seem to work unfortunately... Here is the current `vite` I am using:
![image](https://user-images.githubusercontent.com/740025/190331816-026b5a74-55bc-4d1b-b398-8f10e7a49966.png)

**Comment by btd** [comment]
Problem is that you have 2 rollup versions, and it seems 2.79 are in root. I hoped vite 3.1 will update rollup, but it seem they did not. That change created so much mess. 
I will see if i can reorganize type structure, but i am worry it will be not possible until vite will align with last version of rollup. 
As workaround you can pin rollup to 2.78 or just cast plugin to PluginOptions

**Comment by btd** [comment]
I will probably close this as on my side there is no anything i can do for now. This issue actually must be created on vite+rollup side as they created mess with last releases.
Vite 3.1 limit rollup version to 2.78.x
Most of rollup plugins has rollup in peerDependencies, and a lot of them do not have complimentary meta entry to mark it optional. This causes always 2 rollup installations. One for vite and one for plugin.
I fixed this in this plugin, but this could be caused now by any plugin now it seems. Which one will install rollup in the root first.
If never installed in the root, when ts will see config for vite will use it its types.
