### ISSUE TITLE
can't specify directory to file path.

### ISSUE THREAD

**Issue by shrynx** [btd/rollup-plugin-visualizer#13]
in the filename option currently it is not possible to provide directories as part of file path.
for eg:
```js
...
  plugins: [
   visualizer({
      filename: './deeply/nested/file/index.html',
      ...
]
...
```
the above is currently not possible.
i made a PR implementing this feature https://github.com/btd/rollup-plugin-visualizer/pull/12

**Comment by shrynx** [comment]
Please do consider this feature and if there are any changes required in the PR, then notify.

**Comment by shrynx** [comment]
@btd Please do consider this feature and if there are any changes required in the PR, then notify.

**Comment by shrynx** [comment]
closed by https://github.com/btd/rollup-plugin-visualizer/pull/12

**Comment by schickling** [comment]
Seems like neither relative nor absolute file paths are allowed. Why?

**Comment by btd** [comment]
@schickling both works fine. Create new issue with complete description of problem. Ideally in your case with repro example
