### ISSUE TITLE
Rollup 3.0.0 support

### ISSUE THREAD

**Issue by willeastcott** [btd/rollup-plugin-visualizer#133]
When upgrading [PlayCanvas](https://github.com/playcanvas/engine) to [Rollup 3.0.0](https://github.com/rollup/rollup/releases/tag/v3.0.0), I get:

```
npm WARN Could not resolve dependency:
npm WARN peerOptional rollup@"^2.0.0" from rollup-plugin-visualizer@5.8.2
npm WARN node_modules/rollup-plugin-visualizer
npm WARN   dev rollup-plugin-visualizer@"^5.8.2" from the root project
```

Perhaps this warning is harmless, but even if this plugin is compatible, `peerDependencies` should probably be updated.

**Comment by btd** [comment]
Hi. Rollup3 only recently published. It contains quite a lot of breacking changes. I need to test it first before allowlist it in peer dependencies. 
Just for common understanding versions listed in peer dependencies are there for a reason. I only guarantee it works with this versions.

**Comment by lllopo** [comment]
+1

**Comment by btd** [comment]
My quick tests shows that nothing broke. I will think how to make test for rollup 3

**Comment by btd** [comment]
Updated peer dependencies in new patch version.
