### ISSUE TITLE
Files claiming that they are imported by themselves with an "?commonjs-proxy" extention

### ISSUE THREAD

**Issue by CurtisHumphrey** [btd/rollup-plugin-visualizer#137]
stats.html sent along with stats.json

- Using via vite - vite.config show below
```js
export const config = {
  plugins: [
    react(),
    visualizer({
      gzipSize: true,
      open: true,
    }),
  ],
{
```

![image](https://user-images.githubusercontent.com/1666609/198340487-23cf3ef0-7f68-47f7-8ca1-428b39b8a01e.png)

- OS version - MacOS 12.6, node v16.16.0

**Comment by btd** [comment]
Hi. It is comming from rollup-plugin-commonjs. All boilerplate code it adds are marked by this id. Vite includes this plugin by default. There is nothing wrong there. Confusion creates only naming (id) of these entries.
