### ISSUE TITLE
Improved exclude/include functionality

### ISSUE THREAD

**Issue by fabiospampinato** [btd/rollup-plugin-visualizer#140]
It'd be awesome if the ability to exclude and include things got improved slightly, but in a way that would make all the difference.

Demo video for better clarity:

https://user-images.githubusercontent.com/1812093/204407696-e48381c7-0809-4026-8c41-c4605fdf1057.mp4

- The exclude field doesn't seem to work as I'd expect it to, I'm not sure what it's matched against. Is it possible to exclude the "node_modules" block in the video above for example? I'm guessing it should be matched against the text we see in the diagrams.
- The include field doesn't seem to do anything at all.
- Clicking on a block makes it marginally bigger, but it would be much much nicer if ctrl/cmd+clicking a block told the diagram to render only that block, kinda like autofilling the "include" field to match only that block. That would improve my experience with this diagram dramatically. I simply have too many files to be able to see things clearly without this feature or something similar.

**Comment by fabiospampinato** [comment]
It looks like the `({ id }) => re.test(id);` function is just never called

**Comment by fabiospampinato** [comment]
I think this:

```
              return isModuleExcluded(data) && !isModuleIncluded(data) ? 0 : 1;
```

Should probably be this:

```
              return isModuleExcluded(data) || !isModuleIncluded(data) ? 0 : 1;
```

**Comment by fabiospampinato** [comment]
Yeah with that tweak it's already much more useful

**Comment by btd** [comment]
Hi, thank you. Let me test it

**Comment by btd** [comment]
I have implemented changes on master. Will shortly release this.

**Comment by fabiospampinato** [comment]
Should I open a dedicated issue for this?

> Clicking on a block makes it marginally bigger, but it would be much much nicer if ctrl/cmd+clicking a block told the diagram to render only that block, kinda like autofilling the "include" field to match only that block. That would improve my experience with this diagram dramatically. I simply have too many files to be able to see things clearly without this feature or something similar.

**Comment by btd** [comment]
Yep. Lets make a separate issue about it.

ср, 21 дек. 2022 г., 21:41 Fabio Spampinato ***@***.***>:

**Comment by jeron-diovis** [comment]
Video in topic shows filter fields using regexp to match module names.
Is that something deprecated and changed since 2022? 
Or maybe there is an option to enable such behavior?
I'd like to have filters working like that instead of picomatch globs.
