### ISSUE TITLE
Toggle for tree-shaked modules in "network" view

### ISSUE THREAD

**Issue by thomasdigby** [btd/rollup-plugin-visualizer#144]
It would be really useful to have a toggle (or an option) that would hide "tree-shaked" (tree-shook?) modules to be hidden from the network view. The image below represents one of our applications, and although the information for sibling/dependent modules is still massively useful for debugging, there's a lot of noise that prevents a clearer picture of the actually included modules that are output in the production build.

Happy to attempt a PR if you agree it could be useful

![image](https://user-images.githubusercontent.com/3226804/208913877-6408e99a-c4c5-4cfd-9bfc-1b88b2244fd5.png)

**Comment by btd** [comment]
Hi. Yes i thought about it in past and even did it, but never pushed.
Problem is that this nodes are necessary for connectivity. If you remove all 0 nodes you will have a lot of not connected components. This defeat purpose of this diagram - to find why something included. I did not found better solution yet

**Comment by thomasdigby** [comment]
> Problem is that this nodes are necessary for connectivity. If you remove all 0 nodes you will have a lot of not connected components.

I did wonder that, but surely all nodes included in the bundle must also have a parent node that is also part of the bundle? Maintaining the same relationship that's visualised in the chart at the moment. Or does that relationship not map 1:1 with the network visualisation?

Could you point me in the direction of files/lines that I need to modify to remove or hide the unused nodes? Would be cool to try it locally even if it doesn't go back into the library 😄

**Comment by btd** [comment]
You can try to modify this line in generated file https://github.com/btd/rollup-plugin-visualizer/blob/master/src/network/index.tsx#L76 they are specifically not minified so i do not think there is a problem.
add something like `if(node.byteLength === 0) continue` i think it will do the thing

**Comment by thomasdigby** [comment]
Thanks, appreciate your time. I'll try it out.

I'll close this for now but maybe open a PR for discussion if I put something together that might be useful
