### ISSUE TITLE
Filtering by clicking

### ISSUE THREAD

**Issue by fabiospampinato** [btd/rollup-plugin-visualizer#145]
Clicking on a block makes it marginally bigger, but it would be much much nicer if ctrl/cmd+clicking a block told the diagram to render only that block, kinda like autofilling the "include"/"exclude" fields to match only that block. That would improve my experience with this diagram dramatically. I simply have too many files to be able to see things clearly without this feature or something similar.

**Comment by fabiospampinato** [comment]
Actually even better than that would be to still make the block larger, but so large that it fills the entire view. With the difference being that one would still be able to filter blocks out this way. Also it may be much easier to implement, since blocks can already be made larger.

**Comment by btd** [comment]
@fabiospampinato is it possible to see screenshot how it looks for you normally and zoomed?

**Comment by fabiospampinato** [comment]
Normal:

<img width="1728" alt="Screen Shot 2022-12-29 at 18 16 53" src="https://user-images.githubusercontent.com/1812093/209987190-dadc3f1f-b329-4728-850a-910891324765.png">

Zoomed on the red block:

<img width="1728" alt="Screen Shot 2022-12-29 at 18 17 01" src="https://user-images.githubusercontent.com/1812093/209987249-16add04a-a9ee-4e05-bc49-fa979488d884.png">

Zoomed on the "nanodash" block in the red block (which is just a single small rectangle in the screenshot above):

<img width="1728" alt="Screen Shot 2022-12-29 at 18 17 32" src="https://user-images.githubusercontent.com/1812093/209987271-edba98d3-886e-4cd5-a93a-fecedbd7b907.png">

I basically can't see much 🤣 I possibly have too many files, but [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) allowed for zooming in and out with the scroll wheel and it worked decently well for my codebase.

With the include field fixed now this plugin is much more useful to me, if the ability to zoom more into blocks with a click was implemented I'd imagine it would be more useful still, possibly more useful than `webpack-bundle-analyzer`.

**Comment by btd** [comment]
Thanks for the pictures. I did implemented zoom like you suggested. When you click on rectangle it increase to whole screen. I experimented a bit with percentages and found it is most stable approach. This should be in 5.9.0

**Comment by fabiospampinato** [comment]
It seems to work really well, now the treemap is much more enjoyable to explore, thank you so much! ❤️
