### ISSUE TITLE
Workers aren't reported

### ISSUE THREAD

**Issue by dested** [btd/rollup-plugin-visualizer#146]
Vite Config: 

```typescript 
import {defineConfig} from 'vite';
import solidPlugin from 'vite-plugin-solid';
import solidLabels from 'babel-plugin-solid-labels';
import {visualizer} from 'rollup-plugin-visualizer';
export default defineConfig({
  server: {
    open: '/',
    port: 3000,
    hmr: true,
  },
  plugins: [
    visualizer({}),
    solidPlugin({
      babel: {
        plugins: [[solidLabels, {dev: process.env.NODE_ENV !== 'production'}]],
      },
    }),
  ],
  build: {
    target: 'es2019',
    minify: process.env.NODE_ENV === 'production',
  },
  worker: {
    format: 'es',
  },
});
```

node 14.19.0
```
"vite": "^4.0.1",
"vite-plugin-solid": "^2.5.0"
"solid-js": "1.6.5",
"babel-plugin-solid-labels": "^0.13.0",
```
- [ ] Windows: ^5.8.3

So vite has the ability to import a worker using ```import GameWorker from './someFile?worker';```. This bundles up all the necessary bits into it's own js file. You can see the details here: https://vitejs.dev/config/worker-options.html. Currently the visualizer does not process on the produced file, which may be out of scope, but I figured it was worth mentioning. I may be interested in creating a pull request if you had any ideas and could point me in the right direction.

Thanks for the great plugin!

**Comment by dested** [comment]
I actually tracked it down. What was happening is it emitted the stats.html file multiple times and overwrite the previous one during the build. The workers emitted first, followed by the main final one! I changed the final name generation to add `Date.now()` to it and it dumped out the worker file appropriately. Unfortunately I'm not sure what a more permanent solution to this problem is as I don't know if the appropriate information will bubble up to the plugin for you to specify the html file or not. 

I will leave this open for you to decide if it is a wont-fix, hopefully this thread will help someone in the future either way!

Again, thanks for the great plugin!

**Comment by btd** [comment]
Add emitFile option. It is written in readme

**Comment by schickling** [comment]
> Add emitFile option. It is written in readme

I'm running into the same problem/situation as @dested described and have tried setting `emitFile: true` but my `stats.html` still only contains info about my main file.

**Comment by btd** [comment]
@schickling please post your config and all details about environment. From your description i have no idea if it is the same problem or not

**Comment by laurentpayot** [comment]
I’m running into the same situation as @schickling and @dested with the `emitFile: true`: no visualization of my worker bundle.
I’m using the [recommended web worker constructor syntax](https://vitejs.dev/guide/features.html#web-workers) but with the query suffix syntax the problem remains.

Here is the relevant section of my Vite config:

```javascript
export default defineConfig({
  // ...
  worker: {
    format: 'es'
  },
  // ...
  plugins: [
    visualizer({
      emitFile: true
    }) as PluginOption,
  ],
})
```

**Comment by schickling** [comment]
Thanks a lot for sharing @laurentpayot. I've just given it a try and it seems to partially work. My project has 8 different kinds of workers and the visualizer plugin now only generates a `index.html` for one of the workers.

**Comment by laurentpayot** [comment]
@schickling did you try also adding the [`emitFile` option](https://github.com/btd/rollup-plugin-visualizer#advanced-options-touch-only-if-you-really-need-it)? (I still do not get what it actually does as it is a mere boolean)

**Comment by schickling** [comment]
> @schickling did you try also adding the [emitFile option](https://github.com/btd/rollup-plugin-visualizer#advanced-options-touch-only-if-you-really-need-it)? (I still do not really understand what it actually does as it is a mere boolean)

I did try the `emitFile` option but it seems to "mess things up" in other ways. If it's possible I wasn't smart enough yet to use it correctly. 😅
