### ISSUE TITLE
`visualizer` is not a function when using default import with `Vite`

### ISSUE THREAD

**Issue by xsjcTony** [btd/rollup-plugin-visualizer#148]
Using `vite`

Reprod link: 
https://stackblitz.com/edit/vitejs-vite-tvgwbd?file=vite.config.ts

try to run `npm run dev`, and the issue is there.

`dts` file says I can use both `named import` and `default export` but seems only `named import` is working as expected.
I actually have another repo with `default import` working but I cannot share it due to privacy issue, But when I want to play more with the plugin, I ran into these issue on another laptop.

```ts
// this works
import { visualizer } from 'rollup-plugin-visualizer'

// but this does not work
import visualizer from 'rollup-plugin-visualizer'
```

**Comment by btd** [comment]
Hi.
Default import is not supported. It is stated in readme

**Comment by xsjcTony** [comment]
@btd Hi, Appreciate the response, but if the default export is not working, why `dts` file is still providing a `default export visualizer`? Shouldn't it get removed?

**Comment by btd** [comment]
It is there to do not break backwards compatibility. If somebody used default nothing changed for them. If they will create issue i will ask them to migrate. In readme it is stated what i am supporting
