### ISSUE TITLE
new Include and Exclude is hard to understand and use

### ISSUE THREAD

**Issue by tjx666** [btd/rollup-plugin-visualizer#149]
I just want to filter lodash chunks, with the latest version, I don't know how to do it.

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/41773861/211900176-998df83c-7679-4753-a70e-0f041d46e544.png">

I try following input, but result doesn't expected.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/41773861/211900395-8ca4accf-b079-4bf5-acbb-2f168a87278e.png">

In old version 5.8.3, I just need input exlcude: `.`, include: `lodash`:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/211903625-8e70e060-6421-4b4b-8bdd-ec8e9e013668.png">

Maybe another issue, After I empty the inputs, there is no result:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/41773861/211900637-486c0001-99ba-4cfb-9aa2-ef1db83825d8.png">

The description is also very confused:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/41773861/211900766-4aea3b54-d516-4ecc-ba91-2ce3ba91146a.png">

It means it support input `bundle-*:*` ?

Versions:

```
Packages:
    "rollup": "^3.9.1",
    "rollup-plugin-visualizer": "^5.9.0"
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 158.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
```

**Comment by vaynevayne** [comment]
same as

**Comment by btd** [comment]
I am closing this. As i am not going to work on this. If anyone want to provide feedback on how it should be done, instead of rant - very welcome to issues and PR.

**Comment by tjx666** [comment]
My expect behavior is just the version before 5.9.0. Seems 5.9.0 change the filter behavior a lot

**Comment by stereokai** [comment]
@btd is there any documentation anywhere that explains how to use the filters? Thanks :)

**Comment by danielpza** [comment]
I cannot get the exclude/include filters to work. I don't want to repeat the previous comment but I really have no clue how it works.

**Comment by btd** [comment]
There is unit test for this https://github.com/btd/rollup-plugin-visualizer/blob/master/shared/create-filter.test.ts
If you want create PR to update readme.

I perfectly understand that this change was very controversial. But i think it provides more flexibility in general way. You can search there was tickets about previous input/output filters also. 

To me it looks like what ever i do people will complain. So until i see any reasonable proposal i am not going to change anything in this. I spend on this plugin my free time (you can see when first commit was done and how many years i am doing this for free), i do not receive any PRs or donations. I even do not use to for my daily work as it was in past. And still trying to provide support and maintenance.

**Comment by danielpza** [comment]
Thank you @btd. This makes it a lot clearer.

**Comment by stereokai** [comment]
@btd Wow, thank you very @btd, that's very thoughtful of you. I had figured it out by then but the addition to the readme will definitely come in handy later since I had also already forgotten 😆
