### ISSUE TITLE
Breaks with Rollup v0.60

### ISSUE THREAD

**Issue by NeoLegends** [btd/rollup-plugin-visualizer#15]
Hey!

Our CI deployments are failing (or rather, the Greenkeeper PR upgrading Rollup to v0.60), because this plugin is not compatible anymore.

This line is the issue, `bundle.modules` isn't defined in v0.60 anymore.
https://github.com/btd/rollup-plugin-visualizer/blob/94b7a5c2a567e5ea8b2f82ecf2b944ad2cb20478/plugin.js#L55

**Comment by btd** [comment]
Ok, thanks, i will take a look today.

**Comment by NeoLegends** [comment]
Btw I also found the plugin doesn‘t work properly when code splitting is on. Might wanna take a look at that as well :)

**Comment by btd** [comment]
@NeoLegends i fixed plugin for >= 0.60, but did not yet fixed for code splitting case (yep i know about this problem). I just not very sure how stats file should look in case of multi entries. Maybe several circles one after another?

**Comment by btd** [comment]
I made plugin currently show multiple cicrles in case of several targets.
