### ISSUE TITLE
seperate the file path to another line

### ISSUE THREAD

**Issue by tjx666** [btd/rollup-plugin-visualizer#150]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/211904027-cf9ddea1-9bfa-4971-9a63-7ffff61df0b3.png">

Versions:

```
Packages:
    "rollup": "^3.9.1",
    "rollup-plugin-visualizer": "^5.9.0"
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 158.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
```

**Comment by btd** [comment]
Aggregated issue https://github.com/btd/rollup-plugin-visualizer/issues/183

**Comment by btd** [comment]
btw: you can remove prefix of module if you set correct `projectRoot`. It looks like you either overwrote it or uses not current dir to run your project tools
