### ISSUE TITLE
Broken include/exclude filters

### ISSUE THREAD

**Issue by fabiospampinato** [btd/rollup-plugin-visualizer#152]
The include and exclude filters seem completely broken.

Nothing is excluded with this filter (or any other filter I tried):

<img width="1728" alt="Screen Shot 2023-01-14 at 22 16 43" src="https://user-images.githubusercontent.com/1812093/212499583-0e7ded30-bae1-417d-8b21-52c461555064.png">

Nothing is included with this filter (or any other filter I tried):

<img width="1728" alt="Screen Shot 2023-01-14 at 22 16 49" src="https://user-images.githubusercontent.com/1812093/212499590-f3e4b3d4-ac63-457c-8760-0e8274d9cf2f.png">

Treemap: [rpv.html.zip](https://github.com/btd/rollup-plugin-visualizer/files/10418977/rpv.html.zip)

**Comment by kkrizzz** [comment]
Yep, agree. I discovered the correct syntax for this, which is **/fflate*/** in the include field, but it seems much clunkier compared to using regular expressions previously.

**Comment by jeron-diovis** [comment]
It would be way way easier if filter value was just used for `new RegExp(...)`, directly. Dropping the "feature" of "filter by bundle name" with that semicolon separator.
With regexp we would know what to expect. While memorizing this mess of slashes and stars is literally impossible.

**Comment by btd** [comment]
Hi everyone. I do not have possibility any time soon to look on the
problem. If anyone want to propose solution and property implement it go
ahead. I will happily consider PR.

чт, 9 февр. 2023 г., 15:34 Andrey Bobukh ***@***.***>:

**Comment by btd** [comment]
I am closing this. As i am not going to work on this. If anyone want to provide feedback on how it should be done, instead of rant - very welcome to issues and PR.

**Comment by jeron-diovis** [comment]
Calling an issue a "rant", and then expecting to receive "issue instead of rant". 
Hmm. Good luck with that.

You can get a "feedback on how it should be done" by reading the text of comments above, btw.
