### ISSUE TITLE
Improved support for zooming in and out with a click

### ISSUE THREAD

**Issue by fabiospampinato** [btd/rollup-plugin-visualizer#153]
When clicking on a block it gets enlarged to more clearly reveal its contents, which is great, but when clicking on the currently enlarged block the treemap is not restored to the _previous_ state, but to the default state, which makes for example zooming into a bunch of blocks inside another block, one after the other to inspect them, fairly inconvenient.

Like there's no mechanism to "go back" basically, one can only go kind of restart the chart.

https://user-images.githubusercontent.com/1812093/212499711-1a06083f-0179-450d-9da5-58c1f3d7da66.mp4

Treemap: [rpv.html.zip](https://github.com/btd/rollup-plugin-visualizer/files/10418993/rpv.html.zip)

**Comment by btd** [comment]
Closing, this is already there. If you click on highlighed block - it will shrink back.
