### ISSUE TITLE
Cannot tell module ID because the import list is too long

### ISSUE THREAD

**Issue by gajus** [btd/rollup-plugin-visualizer#154]
A clear and concise description of what you want to happen. If it is change to template, provide the picture of your current template.

https://ibb.co/3S5k6Cj

This image illustrates it.

**Comment by gajus** [comment]
A simple "workaround" would be to dump module info into console when it is clicked. This would not even require modifying the template.

**Comment by btd** [comment]
Hi, cannot see image. Do you mind to provide PR, i do not have time to work even on it any time soon. You can go fancy and use different console methods and styles.

**Comment by btd** [comment]
Aggregated issue https://github.com/btd/rollup-plugin-visualizer/issues/183
