### ISSUE TITLE
Exclude is not working with Vite

### ISSUE THREAD

**Issue by ShivamJoker** [btd/rollup-plugin-visualizer#159]
My config looks like:

```ts
import { defineConfig } from "vite";
import preact from "@preact/preset-vite";
import { visualizer } from "rollup-plugin-visualizer";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    preact(),
    visualizer({
      template: "sunburst",
      exclude: {
        bundle: "**/@aws-sdk/**",
        file: "**/node_modules/@aws-sdk/**",
      },
      open: true,
      gzipSize: true,
      brotliSize: true,
    }),
  ],
});
```

I can still see the AWS modules in the visualize page:
![image](https://user-images.githubusercontent.com/23727670/226146758-4df71531-e77c-44ac-be67-83f4619b8e77.png)

Using Arch Linux

```json
  "dependencies": {
    "preact": "^10.13.0",
    "preact-router": "^4.1.0"
  },
  "devDependencies": {
    "@aws-sdk/client-sesv2": "^3.292.0",
    "@aws-sdk/types": "^3.292.0",
    "@preact/preset-vite": "^2.5.0",
    "rollup-plugin-visualizer": "^5.9.0",
    "typescript": "^4.9.3",
    "vite": "^4.2.0"
  }
```

If you cannot provide me stats html file, provide **all** of this:

- [x] Provide your rollup config (this is most important, because some plugins changes paths to files)
- [x] Provide your node and dependencies versions
- [x] Your OS type and version
- [x] Screenshot of problem

If you do not follow template, issue will be closed without comment.

**Comment by btd** [comment]
You put bundle name with slashes. But your bundle name does not have them. Just remove slashes and use one star one both sides
