### ISSUE TITLE
Typings error

### ISSUE THREAD

**Issue by Fuzzyma** [btd/rollup-plugin-visualizer#162]
I am using vite and just upgraded from 4.0.x to 4.3.x. It turns out that the typings must have changed because typechecks fail now:

![grafik](https://user-images.githubusercontent.com/3540542/236810944-532f29f8-8ebe-4403-825f-939632259c85.png)

```
Type 'import("/my/path/node_modules/rollup/dist/rollup").ObjectHook<(this: import("/my/path/node_modules/rollup/dist/rollup").PluginContext, options: import("/my/path/node_modules/rollup/dist/rollup").NormalizedOutputOptions, bundle: import("/my/path/node_modules/rollup/dist/rollup").OutputBundle, isWrite: boolean) => void | Promise<void>, {}> | undefined' is not assignable to type 'import("/my/path/node_modules/vite/node_modules/rollup/dist/rollup").ObjectHook<(this: import("/my/path/node_modules/vite/node_modules/rollup/dist/rollup").PluginContext, options: import("/my/path/node_modules/vite/node_modules/rollup/dist/rollup").NormalizedOutputOptions, bundle: import("/my/path/node_modules/vite/node_modules/rollup/dist/rollup").OutputBundle, isWrite: boolean) => void | Promise<void>, {}> | undefined'.
```

**Comment by btd** [comment]
Yes it is know issue of vite. In rollup 3.x was a breaking change in types. Vite copied types from rollup, but did not specified version.
Just add casting to PluginOptions
See https://github.com/btd/rollup-plugin-visualizer/issues/124 and https://github.com/btd/rollup-plugin-visualizer/issues/127
