### ISSUE TITLE
[BUG] Massive size mismatch for minified code

### ISSUE THREAD

**Issue by thoughtspile** [btd/rollup-plugin-visualizer#163]
We're facing a similar problem to #96 — the module / chunk sizes reported by plugin-visualizer are overestimated by 2-3x. I built a [reproduction with a 5x overestimation when bundling date-fns](https://github.com/thoughtspile/rollup-bundle-visualizer-repro)

I'm pretty sure this is caused by using non-minified modules for size computation — reported size is very close to the bundle size without terser. This is very problematic for several reasons:

- Such massive overestimation can cause useless optimization. In our production app, the reported date-fns size was around 30kB gzip, while the real size was around 3.5kB.
- Most production bundles are minified. Accounting for it is a necessity, not a bonus.
- The relative sizes of different modules (especially libraries) are skewed, depending on whether the dist is minified and commented. Using only percents, as suggested in #98, won't work.
- For ESM bundles where a lot of dead code is eliminated during tree-shaking, the overestimation can be even bigger.

`sourcemap` plugin option has no major effect (~45 bytes) — both the original module in the FS and the sourcemap version are non-minified.

Using `renderedLength` as reported by rollup in [plugin/index.js](https://github.com/btd/rollup-plugin-visualizer/blob/f70d2e5a0bc94ac009954b1d6a3e987f759f9d41/plugin/index.ts#L183) gives a much better result. [From what I hear,](https://github.com/btd/rollup-plugin-visualizer/issues/96#issuecomment-817093773) this method underestimates the size of unicode strings, and the reported size is indeed a bit smaller for our production app with cyrillic texts, but nowhere close to 5x.

I'd suggest adding a `renderedLength: boolean` option to report more realistic sizes under minification. Unicode-adjusted estimation can be added later.

For now, we'll work around the issue using [patch-package](https://github.com/ds300/patch-package) on plugin-visualizer to use raw `renderedLength`.

**Comment by thoughtspile** [comment]
Actually, I've made a mistake: `sourcemap: true` correctly computes `renderedLength`, but later it's dismissed in `ModuleLengths`. 

This computation can be better adjusted for unicode by this change in `getBytesPerFileUsingSourceMap`:

```diff
- modules[id].renderedLength += 1;
+ modules[id].renderedLength +=  Buffer.byteLength(code[i], "utf-8");`
``` 

Ran additional tests on `date-fns/locale` (a lot of unicode), here are the results:

1. Actual bundle size: 611kB
2. Reported: 990kB (162% actual), regardless of `sourcemap` option.
3. Reported using rollup's `renderedLength` and `sourcemap: false`: 915kB (149% actual)
4. Reported using `renderedLength` from current `sourcemap: true`: 521kB (85% actual)
5. Reported using `renderedLength` with unicode-adjusted `sourcemap`: 957kB (98% actual)

I'm not sure where the remaining 14kB comes from, but it's reasonably close to the actual size. How would you feel about using `renderedLength` when `sourcemap` option is enabled, and adding unicode adjustment I propose?

**Comment by btd** [comment]
Hi. First of all Thanks for every detailed issue.
Yes reportered size always different from actual one. Closest you can get to reality with sourcemap option set to true.
I should say i never tried to use non ascii chracters. 
It would be nice if you will make PR and i will take a look. Otherwise no ETA.
Also i am curious if we should use codePointAt or anything that correctly traverse code points. Random index could point in the middle of surrogate pair

**Comment by btd** [comment]
I have published 5.9.2. Take a look pls if it improves size reporting with sourcemap.

**Comment by r-thomson** [comment]
> I have published 5.9.2. Take a look pls if it improves size reporting with sourcemap.

Heads up,[ 5.9.2 seems to be missing from the changelog](https://github.com/btd/rollup-plugin-visualizer/blob/64137b5607bd56ae6f371ef8de900ee2cc0c4dcb/CHANGELOG.md)

**Comment by jasonaden** [comment]
> > I have published 5.9.2. Take a look pls if it improves size reporting with sourcemap.
> 
> Heads up, [5.9.2 seems to be missing from the changelog](https://github.com/btd/rollup-plugin-visualizer/blob/64137b5607bd56ae6f371ef8de900ee2cc0c4dcb/CHANGELOG.md)

I think it was supposed to say `5.9.1` since that was published 4 days ago and sounds like it matches this issue.

**Comment by r-thomson** [comment]
> > Heads up, [5.9.2 seems to be missing from the changelog](https://github.com/btd/rollup-plugin-visualizer/blob/64137b5607bd56ae6f371ef8de900ee2cc0c4dcb/CHANGELOG.md)
> 
> I think it was supposed to say `5.9.1` since that was published 4 days ago and sounds like it matches this issue.

Except [there was a 5.9.2 published](https://www.npmjs.com/package/rollup-plugin-visualizer/v/5.9.2)

**Comment by btd** [comment]
The difference between 5.9.2 and 5.9.1 is that i dropped 14.x from test matrix

**Comment by HummingMind** [comment]
This doesn't report the correct sizes.
vite-bundle-analyzer does not have this problem (although it's a Vite plugin, not a rollup plugin).

Would be nice to see a fix.

Thank you! 🍻

**Comment by Haroenv** [comment]
For anyone that wants a quick workaround to have mostly useful numbers, it seems like `sourcemap: true` uses sizes post minification
