### ISSUE TITLE
No stats for CSS files in the build output

### ISSUE THREAD

**Issue by jasonaden** [btd/rollup-plugin-visualizer#165]
I started with an empty (Vanilla) Vite project using `yarn create vite` command. Selected the "Vanilla" option and then added the vite.config file in the gist below. When building the project, the stats file has no reference to the CSS file output into the `dist/local` directory.

Stats file and vite config: https://gist.github.com/jasonaden/f38a7a38cea4fb8ff6b5ea71d9fcfcb7

**Comment by btd** [comment]
Hi, can you clarify what do you mean 'stats file has no reference to the CSS file'?

I can see css file in stats, it is small but it is there

**Comment by btd** [comment]
Closing
