### ISSUE TITLE
No affordances for what can be clicked

### ISSUE THREAD

**Issue by kaiyoma** [btd/rollup-plugin-visualizer#168]
It's not clear what can be clicked in the rendered page, because the mouse cursor never turns to a pointer. The mouse cursor actually turns to a "select" cursor when hovering over text, which is confusing, because this text can also be clicked.

**Comment by btd** [comment]
Good idea, do you want to create PR?

**Comment by btd** [comment]
Added cursor pointer over nodes to 5.11.0
