### ISSUE TITLE
renderedLength from sourcemaps is ignored, pre-plugins module sizes are used instead

### ISSUE THREAD

**Issue by t2t2** [btd/rollup-plugin-visualizer#169]
Yep it's continuation of #163 (and externally KusStar/vite-bundle-visualizer#8)

Even after 442517c the sizes in the report mismatch with final output, especially when using minifier (eg. terser). Simple test case:

`index.js` (size: 117 bytes, no tailing newline)
```js
/* This is a long comment that any terser should remove from final output */
const message = 'hello';
alert(message);
```

`rollup.config.mjs:`
```js
import terser from '@rollup/plugin-terser';
import { visualizer } from 'rollup-plugin-visualizer';

export default {
  input: 'index.js',
  output: {
    dir: 'output',
    format: 'cjs',
    sourcemap: true
  },
  plugins: [
    terser(),
    visualizer({
      sourcemap: true,
      template: 'list',
    }),
  ]
};
```

rollup output `output/index.js`: (size 63 bytes)
```js
"use strict";alert("hello");
//# sourceMappingURL=index.js.map
```

rollup-plugin-visualizer output `stats.yml`:

```yml
index.js:
  \index.js:
    rendered: 117
```

117 is more than 63 and suspiciously close to source file size, so I took debugger and figured out why.

---

When looking at the ModuleLengths function, [it prefers using the length of code compared to renderedLength](https://github.com/btd/rollup-plugin-visualizer/blob/64137b5607bd56ae6f371ef8de900ee2cc0c4dcb/plugin/index.ts#L183C11-L183C91), however debugger reveals that the code used is the raw, unprocessed by plugins source of the module. renderLength calculated from sourcemap is correct (16 = length of `alert("hello");`+newline):

![image](https://github.com/btd/rollup-plugin-visualizer/assets/1122555/42aebc96-7797-4470-8af1-d7e9af056a29)

code is taken from [output bundle modules](https://github.com/btd/rollup-plugin-visualizer/blob/64137b5607bd56ae6f371ef8de900ee2cc0c4dcb/plugin/index.ts#L218), and debugger confirms that this is indeed from before all plugins:

![image](https://github.com/btd/rollup-plugin-visualizer/assets/1122555/f62c5c93-9197-41a3-bbdf-76b6d0db23bd)

---

There seems to be 2 potential approaches to fix:

The quick and dirty fix is to just use renderedLength (idk if length from code is needed as fallback?)
```diff
        const result = {
          id,
          gzipLength: isCodeEmpty ? 0 : await gzipSizeGetter(code),
          brotliLength: isCodeEmpty ? 0 : await brotliSizeGetter(code),
--          renderedLength: isCodeEmpty ? renderedLength : Buffer.byteLength(code, "utf-8"),
++          renderedLength: renderedLength || (isCodeEmpty ? 0 : Buffer.byteLength(code, "utf-8")),
        };
        return result;
```

stats.yml:
```
index.js:
  \index.js:
    rendered: 16
```

(note: [in the sourcemap the `"use strict";` and sourceMappingURL are unmapped](https://sokra.github.io/source-map-visualization/#base64,InVzZSBzdHJpY3QiO2FsZXJ0KCJoZWxsbyIpOwovLyMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5qcy5tYXAK,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VzIjpbIi4uL2luZGV4LmpzIl0sInNvdXJjZXNDb250ZW50IjpbIi8qIFRoaXMgaXMgYSBsb25nIGNvbW1lbnQgdGhhdCBhbnkgdGVyc2VyIHNob3VsZCByZW1vdmUgZnJvbSBmaW5hbCBvdXRwdXQgKi9cbmNvbnN0IG1lc3NhZ2UgPSAnaGVsbG8nO1xuYWxlcnQobWVzc2FnZSk7XG4iXSwibmFtZXMiOlsiYWxlcnQiXSwibWFwcGluZ3MiOiJhQUVBQSxNQURnQiJ9,LyogVGhpcyBpcyBhIGxvbmcgY29tbWVudCB0aGF0IGFueSB0ZXJzZXIgc2hvdWxkIHJlbW92ZSBmcm9tIGZpbmFsIG91dHB1dCAqLwpjb25zdCBtZXNzYWdlID0gJ2hlbGxvJzsKYWxlcnQobWVzc2FnZSk7Cg==), so it showing slightly lower value than bundle size is kinda normal)

Other option is to read the actually rendered code from sourcemap and use it instead of `bundle.modules[id].code`. This is actually something #164 did, but seems like long feedback cycle and some misunderstandings in review got @thoughtspile to abandon it. But as seen by PR, this is the better approach as it also allows gzip and brotli sizes of modules in sourcemap mode (even if those are misleading as gzip + brotli sizes are highly influenced by how much repeating code there is, but the same issue also applies to `sourcemap: false` mode)

---

So I created this issue to check if it's better to

- just quickly fix it to use renderedLength over code length
- get #164 into mergable state?

**Comment by btd** [comment]
Thank you for deep investigation. This place changed so much i already do not remember all edge cases. I will take a look. But no any ETA

**Comment by btd** [comment]
Added fix for sourcemap build. Thanks again for details in issue, it really helped
