### ISSUE TITLE
Add an 'open' option

### ISSUE THREAD

**Issue by Makio64** [btd/rollup-plugin-visualizer#17]
Hi,

Will be nice to add an option who start the page in the browser after the generation.

Cheers,

D

**Comment by btd** [comment]
Sounds good. I will see what i can do there. Also i will not be able to test it on each platform (i am on win).

**Comment by Makio64** [comment]
I can test it on mac/win10 if needed
Also I think this might help: https://www.npmjs.com/package/open

**Comment by btd** [comment]
Done in 0.9.0

**Comment by romanlex** [comment]
@btd can you make exit(0) from build process when stats file is will be opened in the browser
