### ISSUE TITLE
Rollup 4.x

### ISSUE THREAD

**Issue by rejhgadellaa** [btd/rollup-plugin-visualizer#172]
`rollup-plugin-visualizer` doesn't have `rollup >= 4.0.0` as a valid peer dependency, preventing the use of the latest rollup release.

```
npm WARN Could not resolve dependency:
npm WARN peerOptional rollup@"2.x || 3.x" from rollup-plugin-visualizer@5.9.2
```

**Comment by epreston** [comment]
If you want a quick fix while changes are reviewed, you can override the dep.

`package.json`
```json
{
  "devDependencies": {
    "rollup":"^4.5.0",
  }
  "overrides": {
    "rollup-plugin-visualizer": {
      "rollup": "$rollup"
    }
  }
}
```

This will make visualizer use the version you have in your dev deps.

**Comment by tonygustafsson** [comment]
Not sure if it's related, but using it as a Vite 5 plugin doesn't work according to TypeScript:

![image](https://github.com/btd/rollup-plugin-visualizer/assets/7383255/97372c1a-0cc3-43f4-a292-112d18271776)

**Comment by epreston** [comment]
@tonygustafsson Separate issue. Typescript cant determine the type.  Works well.

**Comment by xsjcTony** [comment]
Yeah the plugin works well, but I think the type issue should be fixed as well

**Comment by epreston** [comment]
Happy to post the solution if it is raised under a new issue.
