### ISSUE TITLE
Compare with list of chunks

### ISSUE THREAD

**Issue by eMerzh** [btd/rollup-plugin-visualizer#174]
Hello, 

trying to analyze the first load of our app , i find this plugin really usefull
But as the code splitting get better, i start to have a bunch of chunks, and looking at first few chunks loaded, it"s hard to know what exactly is loaded on first chunk (and thus detect things that could be delayed or removed)

I was thinking about allowing to filter via a list of names or something? 

is that already possible and i missed it?

**Comment by btd** [comment]
there are include and exclude filters both on plugin level and ui (nobody likes ui version in some reason). Please try it out.
