### ISSUE TITLE
Make output idempotent

### ISSUE THREAD

**Issue by janpio** [btd/rollup-plugin-visualizer#177]
It would be great if the generated HTML output would only change if the actual data changes. Right now the data contains some random IDs that change with each run:

<img width="1589" alt="image" src="https://github.com/btd/esbuild-visualizer/assets/183673/71dc664b-e8f5-462a-9fa0-e304217173ec">

I commit the resulting files to Git, and it would be amazing if I could use the git diff as an indication that something actually changed.

**Comment by btd** [comment]
Added hash based prefix to both places. In esbuild plugin it should be stable as file never changes, in rollup there is some (i got few values running build several times, seems order or something changed, did not yet figured it out) randomness that is comming from rollup
