### ISSUE TITLE
Does not seem to work on rollup 0.59.2

### ISSUE THREAD

**Issue by wilomgfx** [btd/rollup-plugin-visualizer#18]
I don't see any html file created at all.

**Comment by btd** [comment]
@wilomgfx 0.59.2 quite old from api perspective. I do not remember exactly but from some version they changed api for plugins, so latest version of this plugin support only more/less recent rollup releases.

**Comment by wilomgfx** [comment]
Oh did not notice my version was that far haha! I'll retry with the latest haha!

**Comment by wilomgfx** [comment]
works, sorry for the waste of time haha :)

**Comment by btd** [comment]
no problem. 👍
