### ISSUE TITLE
✕ unmet peer rollup@^2.56.3: found 3.29.4

### ISSUE THREAD

**Issue by lxccc812** [btd/rollup-plugin-visualizer#181]
Share with me your stats html file. It does not contain your source code - it is completely safe. You can send it to my email (see my github profile).

If you cannot provide me stats html file, provide **all** of this:

logs 
✕ unmet peer rollup@^2.56.3: found 3.29.4

```shell
System:
  OS: Windows 11 10.0.22621
  CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
  Memory: 2.37 GB / 15.19 GB
Binaries:
  Node: 18.18.2 - D:\nvm\nodejs\node.EXE
  npm: 9.8.1 - D:\nvm\nodejs\npm.CMD
  pnpm: 8.9.2 - D:\nvm\nodejs\pnpm.CMD
Browsers:
  Edge: Chromium (119.0.2151.97)
  Internet Explorer: 11.0.22621.1
npmPackages:
  @vitejs/plugin-vue: ^4.5.2 => 4.5.2
  @vitejs/plugin-vue-jsx: ^3.1.0 => 3.1.0
  rollup: ^3.29.4 => 3.29.4
  vite: ^4.5.1 => 4.5.1
```

- [ ] Provide your rollup config (this is most important, because some plugins changes paths to files)
- [x] Provide your node and dependencies versions
- [x] Your OS type and version
- [ ] Screenshot of problem

If you do not follow template, issue will be closed without comment.

**Comment by btd** [comment]
Well, add at least what your are doing. You see last item with checkbox, it is there so i would not guess
