### ISSUE TITLE
5.11.0 new strict mode not allowing files in CLI command

### ISSUE THREAD

**Issue by Ma-An** [btd/rollup-plugin-visualizer#186]
New version 5.11.0 has strict mode added to CLI, this seems to be causing issues with CLI command not allowing files anymore.

Here I run command on 5.9.0: 
`$ rollup-plugin-visualizer --filename ./bundle-stats/stats.html --template sunburst --open true ./bundle-stats/stats.json 
✨  Done in 0.36s.`

Running command on 5.11.0:
`$ rollup-plugin-visualizer --filename ./bundle-stats/stats.html --template sunburst --open true ./bundle-stats/stats.json 
Unknown argument: ./bundle-stats/stats.json`

Removing strict mode in CLI fixes issue and allows command to run on 5.11.0

**Comment by btd** [comment]
Hi, thanks. I fixed it in master, but forgot to publish. Just published 5.12
