### ISSUE TITLE
`open` flag does not work if `emitFile` is `true`

### ISSUE THREAD

**Issue by brookslybrand** [btd/rollup-plugin-visualizer#187]
Not sure if this is a bug or a feature, but it'd be nice if `open` worked with `emitFile`

[Looks like right now it's an either or](https://github.com/btd/rollup-plugin-visualizer/blob/master/plugin/index.ts#L291-L308)

**Comment by btd** [comment]
Yes it is intentional. EmitFile give file to rollup to place where it is appropriate. There is way to know where the file will appear for plugin and i do not want to copy rollup parts to calculate it.
