### ISSUE TITLE
support esm fully

### ISSUE THREAD

**Issue by SKT1yang** [btd/rollup-plugin-visualizer#194]
environment：vite 5.2.13, node 18.17.0.
Vite v5 or above requires the package to fully support ESM, otherwise it cannot run directly.
![image](https://github.com/btd/rollup-plugin-visualizer/assets/34095649/3b9ad619-ec2f-4dec-b600-1cfe3a78425a)

**Comment by btd** [comment]
From ESM code you can import non-esm code via default import only.
