### ISSUE TITLE
Script only for visualizer

### ISSUE THREAD

**Issue by camila-frangp** [btd/rollup-plugin-visualizer#195]
I need to set up a script that runs only this plugin and not for each build, because my project is a library (monorepo) with lerna, so it generates 1 build for each component for each `npm run build`

```js
    visualizer({
      open: true,
    }),
```

**Comment by btd** [comment]
Sorry, but what is actual question there?

**Comment by meri-maki** [comment]
Hello! Also encounter a need to run this plugin on another script (not `npm run build`)
How can I run the visualiser on `npm run visualize` for example?

**Comment by camila-frangp** [comment]
Exactly, what @meri-maki asks for is what I need.

**Comment by btd** [comment]
Sorry people i still have no idea what you ask. Closing unless you provide me more data
