### ISSUE TITLE
rollup-plugin-visualizer的emitFile和open同时为true时，可视化文件会生成在打包文件底下，而浏览器没有自动打开该文件；emitFile为false，open为true时，可视化文件在根目录底下，浏览器自动打开该文件。这是为什么呢？

### ISSUE THREAD

**Issue by zydwlt** [btd/rollup-plugin-visualizer#196]
Share with me your stats html file. It does not contain your source code - it is completely safe. You can send it to my email (see my github profile).

If you cannot provide me stats html file, provide **all** of this:

- [ ] Provide your rollup config (this is most important, because some plugins changes paths to files)
- [ ] Provide your node and dependencies versions
- [ ] Your OS type and version
- [ ] Screenshot of problem

If you do not follow template, issue will be closed without comment.

**Comment by zydwlt** [comment]
1、使用的vite打包。
2、rollup-plugin-visualizer的配置
  visualizer({
      filename: 'view.html',
      // template: 'treemap',
      gzipSize: true,
      brotliSize: true,
      emitFile: true,
      open: true,
    }),
3、"node":16.18.1
4、 "rollup-plugin-visualizer": "^5.12.0",
5、rollup-plugin-visualizer的emitFile和open同时为true时，可视化文件会生成在打包文件底下，而浏览器没有自动打开该文件；emitFile为false，open为true时，可视化文件在根目录底下，浏览器自动打开该文件。这是为什么呢？

**Comment by btd** [comment]
This is drawback of emitFile.

When emitFile used - file generation delegated to rollup and it put it according output settings. As i do not know final path of file i cannot open it.

So sorry, i cannot do with this anything. I looked on this before. AFAIK nothing changed in plugin API
