### ISSUE TITLE
No chart when single file with no dependencies is used

### ISSUE THREAD

**Issue by vladshcherbin** [btd/rollup-plugin-visualizer#25]
Hey,

there is no chart when single file is used with no dependencies.

#### input file

```js
console.log('hey')
```

#### after processed with rollup

```js
(function () {
	'use strict';

	console.log('hey');

}());
```

#### result

![rv](https://user-images.githubusercontent.com/6711845/53239530-5122fb80-36ad-11e9-9e79-925e7e88fd51.png)

#### package versions

rollup - 1.2.2
rollup-plugin-visualizer - 1.0.0

I'd expect a chart with 100% :)

**Comment by btd** [comment]
Fixed i think

**Comment by vladshcherbin** [comment]
@btd yep, fixed. Thanks :)
