### ISSUE TITLE
Open option doesn't end build process

### ISSUE THREAD

**Issue by vladshcherbin** [btd/rollup-plugin-visualizer#27]
When `{ open: true }` is used, stats file is opened in a browser, but the build process doesn't end.

Similar issue - https://github.com/btd/rollup-plugin-visualizer/issues/17#issuecomment-464343339

I've updated [test repo](https://github.com/vladshcherbin/experiments/tree/master/visualizer) to reflect this issue.

node - 11.7.0
macOS - 10.13.4

**Comment by btd** [comment]
Why it should end build?

вс, 24 февр. 2019 г., 19:40 Vlad Shcherbin <notifications@github.com>:

**Comment by vladshcherbin** [comment]
@btd why wouldn't it? I thought it would create stats (as default) and just open a browser to see them.

If I don't want to end build I'd use `watch` option, no?

**Comment by btd** [comment]
Well, maybe, not sure. But how in this case plugin should detect if it is running in watch mode and do not stop build?

**Comment by vladshcherbin** [comment]
@btd you can check, if rollup is in watch mode by using `process.env.ROLLUP_WATCH`, it will be `true`

**Comment by btd** [comment]
ok, so it looks i can add option like `throwOnOpen`. i do not want to add `process.exit` because it will exit whole process, even if plugin used programatically (i use at least in this way). This way i do not need to care about `ROLLUP_WATCH`

**Comment by vladshcherbin** [comment]
@btd let's don't rush it and find a good solution.

can you describe a bit how you use it and why do you need it to stay open? maybe [watch](https://rollupjs.org/guide/en#rollup-watch) can help somehow? tell about it :)

**Comment by btd** [comment]
@vladshcherbin i do not use watch, because rollup is only one part of whole build process.

**Comment by btd** [comment]
Closing because of lack of interest
