### ISSUE TITLE
Feature request: Add treemap support

### ISSUE THREAD

**Issue by ziofat** [btd/rollup-plugin-visualizer#30]
Great plugin. I'd like to see an option to control how results to be showed.

Treemap would be a great way to show the whole picture so I can take a screenshot to tell my teammates what should be done.

Like [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) did.

**Comment by btd** [comment]
Well, this is possible but this will take some time.

**Comment by btd** [comment]
Fixed
