### ISSUE TITLE
Error with rollup 0.41.4

### ISSUE THREAD

**Issue by faboweb** [btd/rollup-plugin-visualizer#4]
Hi,
unfortunatly this doesn't seem to work with the stated version of rollup. I get the error:

`Unexpected token {`

**Comment by btd** [comment]
Could you please provide some sort of example what you are trying to do, or better how to reproduce it?

**Comment by faboweb** [comment]
rollup.config.js without visualizer:
https://github.com/faboweb/zliq/blob/rollup-visualizer/rollup.config.js

package.json:
https://github.com/faboweb/zliq/blob/rollup-visualizer/package.json

you could checkout the branch to test yourself.

I don't get any more errors then what I posted. But it appears

**Comment by btd** [comment]
I did not got any errors. I cloned, switched to branch `rollup-visualizer` and run `npm run build`, then just opened stats.html

**Comment by EnoahNetzach** [comment]
I was able to reproduce it, using node **v4**.

If you just require the module, you get that error, with this stack trace:
```
/home/node/node_modules/rollup-plugin-visualizer/plugin.js:17
    ongenerate({ bundle }, rendered) {
               ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:287:14)

```
