### ISSUE TITLE
Treemap support: improve bundles relative display

### ISSUE THREAD

**Issue by JeanRemiDelteil** [btd/rollup-plugin-visualizer#40]
The actual treemap does not allow to compare between all the different bundles:
- all bundles have the same size,
- must scroll all the way down to compare all the sizes.

The great point of webpack-bundle-analyzer was to just allow that: all bundles size are comparable and mean something, also everything in the default display, to have a quick grasp of the bundle situation.

**Comment by btd** [comment]
Well, i initially does not thought about comparing bundles. When i started this plugin, rollup had no support for several bundles.
Probably this really makes sense. I will think about it.

**Comment by btd** [comment]
I added option bundlesRelative, it puts all bundles to common root and use the same diagram to show bundles relative dependencies

**Comment by JeanRemiDelteil** [comment]
Nice !

By the way, it seems like the display with _bundlesRelative_ only shows 1 step deeper into the bundles. Is that by design or is it a bug ?

**Comment by btd** [comment]
If i understand you right, yes it is by design i would say. I provide to d3 tree layout max size for diagram and all nodes, it computes nodes sizes and if they should be shown (because of relative small size).'

Later i will add zooming to these diagrams and fix network graph for bundles.

**Comment by JeanRemiDelteil** [comment]
Wouldn't using the same graphic as webpack-bundle-analyzer which is really great, possible ?

**Comment by btd** [comment]
Nope. webpack-bundle-analyzer uses [FoamTree](https://carrotsearch.com/foamtree/) library. My plugin uses only d3.
I honestly do not see any reason for bringing FoamTree to this project.

**Comment by JeanRemiDelteil** [comment]
a reason: "the end result is really really suitable for this kind of use".
(please take my humble opinion as such :)

**Comment by btd** [comment]
I tend to agree about better looking (but imo it is fixable). I have several reasons to do not use this lib: first it is not FOSS, second i started to use D3 for educational purpose (and consider this plugin as my educational playground), third i do not have time to rewrite it to completely new to me lib.
