### ISSUE TITLE
Support all templates in one file

### ISSUE THREAD

**Issue by clitetailor** [btd/rollup-plugin-visualizer#41]
**What is this?**

This is a feature request.

**Description:**

Instead of having to rebuild `stats.html` for different templates, we can include all visualizer templates in one file:

```js
plugins: [
  visualizer({ template: 'all' })
]
```

**Comment by btd** [comment]
Hmm. How it could look? Each template takes different concepts on visualising data. I just do not see a point how it could be really usefull

**Comment by clitetailor** [comment]
Because the `nodesData` is the same for every templates, so we just need to merge the scripts and put each template into one tab:

![example](https://user-images.githubusercontent.com/16368559/60454296-af647a00-9c5d-11e9-83e0-0b9e95099d60.png)

Just we can have all different views in one time build so why don't we do it anyway!

**Comment by btd** [comment]
Sorry, but this does not convinced me.

Just that something is possible does not mean it should be done. Only 3 of 4 charts has the same structure for d3-hierarchy. And i have plans to change one of these 3 also.

Anyway i will think about it and will rest this open if somebody would like to comment.
