### ISSUE TITLE
Not working starting with version 2.5.1

### ISSUE THREAD

**Issue by pablote** [btd/rollup-plugin-visualizer#42]
Version 2.5.0 works just fine. Here's some screenshots of what I'm seeing:

thanks

![Screen Shot 2019-07-23 at 19 09 09](https://user-images.githubusercontent.com/2463995/61751384-85930480-ad7e-11e9-962b-26073501a38c.png)
![Screen Shot 2019-07-23 at 19 09 27](https://user-images.githubusercontent.com/2463995/61751386-875cc800-ad7e-11e9-89df-8f53f417d2a7.png)
![Screen Shot 2019-07-23 at 19 09 33](https://user-images.githubusercontent.com/2463995/61751391-8a57b880-ad7e-11e9-972e-e3b6985deffc.png)

**Comment by mushroomgead** [comment]
+1 the same issue

**Comment by btd** [comment]
Can you provide me more details: node version, package.json contents, rollup config etc?
Ideally i would like to have reproducible example.
It would be good to have stat file itself.

**Comment by btd** [comment]
Fixed
