### ISSUE TITLE
Is there a way to show minimized (parsed) size

### ISSUE THREAD

**Issue by vedmant** [btd/rollup-plugin-visualizer#43]
Is there a way to show minimized (parsed) size like webpack bundle analyzer does? Gzipped size can be also helpful.

**Comment by btd** [comment]
Hi, good question with not clear answer.

Currently plugin shows parsed size, but this depends where this plugin installed. I will try to explain what does this means:
This plugin uses hook 'generateBundle' - this hook executed one of the latest.
If there are several plugins that uses 'generateBundle' hook, they will be executed in order. Next depends from plugins installed before/after.
Returning to minified size, it is only possible only if terser/uglify plugin installed before as plugin itself do not have access to other plugins.

**Comment by FezVrasta** [comment]
I'm running this plugin after terser, but I still see the unminified bundle size. Ideas?

**Comment by FezVrasta** [comment]
Oh, we need to enable `sourcemap` in the plugin options.
