### ISSUE TITLE
styles example file

### ISSUE THREAD

**Issue by evdama** [btd/rollup-plugin-visualizer#49]
Thanks for this great plugin, much appreachiated! :)

I've got three .json input files, one for each of my bundles, producing one output file using this line in package.json in my sapper project.

```js
  "scripts": {
  ...
    "edm:visualizer": "./node_modules/.bin/rollup-plugin-visualizer --filename \"./visualizer_stats/edm-bundles.html\" --title \"EDM Bundles\" ./visualizer_stats/server.json ./visualizer_stats/client.json ./visualizer_stats/service-worker.json",
...
  }
```
Result looks like this
![Screen Shot 2019-11-15 at 11 04 22](https://user-images.githubusercontent.com/39374084/68934844-c2549280-0797-11ea-90b7-436837e6c54f.png)

Now I'd like to style it using the `extraStylePath` CLI switch in addtion to what I have above.
It would be rather nice to have a template example for such stylesheet to work off rather than starting from scratch. Is there any such example file? Doesn't look like it so far...

My first and foremost desire would be to not have a autogenerated width of currently about 3000px but style it so it scales to the windows width of the browser so I get an overview rather than having to scroll horizontally...

**Comment by btd** [comment]
I honestly not see what it is possible to customize, because most of the things happen at generate svg time.
All of charts uses this [base scss file](https://github.com/btd/rollup-plugin-visualizer/blob/master/src/style/_base.scss). You can see it is pretty generic.

**Comment by evdama** [comment]
ah, ok, I see... I'll fork of this one and style it with tailwind CSS and then use `extraStylePath` to point to it.

**Comment by btd** [comment]
Ok. Share your result please. Maybe something could be integrated.
