### ISSUE TITLE
Default text color in 'light' theme too light

### ISSUE THREAD

**Issue by clintwood** [btd/rollup-plugin-visualizer#56]
Thanks for this plugin!

In recent versions (currently 3.2.2) the default text color (`--text-color`) in 'light' theme for `sunburst` template seems to be too light.  I realize I could provide my own styles but I'd prefer to just use the colors out of the box!

I have emailed my stats file as `clintwood-stats.html`

**Comment by btd** [comment]
I just published 3.2.3 it should be a bit better
