### ISSUE TITLE
Show gzip and brotli sizes

### ISSUE THREAD

**Issue by FezVrasta** [btd/rollup-plugin-visualizer#58]
We are using this tool to optimize parts of the library that are too heavy, it would be great to have a way to use the gzip and/or brotli compressed sizes, so that we can focus on parts of the library that after compression are still too big.

I already encountered a couple cases where I reduced the code of a function, but that didn't reflect in a reduction of the compressed size (but the opposite).

**Comment by btd** [comment]
I understand your point, but this is a little hard to make properly. In hook i use for plugin there is no access to module sources.
I will think how i can implement something like this.

**Comment by FezVrasta** [comment]
Couldn’t you use the file name to get the source code?

**Comment by btd** [comment]
I can this. But as i said results will be very inaccurate. We need source after treeshake and some plugins adds additional files (usually starts with \0000) which there is bo access.

**Comment by FezVrasta** [comment]
Ah correct 🤦‍♂️

**Comment by btd** [comment]
Just to update progress. gzip and brotli supported by master now. I asked Lukas about access to treeshaked source - he said it is possible.

**Comment by btd** [comment]
I published 4.0.0 as beta tag you can try gzip and brotli. But you should manually specify this in options
