### ISSUE TITLE
Working with code splitting

### ISSUE THREAD

**Issue by rvillalba-novetta** [btd/rollup-plugin-visualizer#59]
I don't believe this works with code splitting right now. All I see is an empty output, not sure if its because output.file is not used and output.dir is used instead?

**Comment by btd** [comment]
It works with code splitting defenetly. It looks like a bug. But i cabnot say withou details.
You can provide me stats file to take a look

**Comment by rvillalba-novetta** [comment]
The issue seems to occur here

![image](https://user-images.githubusercontent.com/31288097/70710669-b03e1500-1cad-11ea-9a3b-d1d32f8c1554.png)

Node data has no uuid it only has: {children: [], name: "components/Buttons.js"} 

I have a structure like this:

components
    Buttons
        index.js
        A.js
        B.js

For my input I mapped {components/Buttons: components/Buttons/index.js}

I'm guessing this mapping is the source of the issue?

**Comment by btd** [comment]
This is defenetly an issue. How you did mapping? Can you share this part of rollup config?

**Comment by rvillalba-novetta** [comment]
I've made a minimal example. Here is the src/ structure:

```
==> src/index.js <==
export * from "./components/index";

export const top = "top";

==> src/components/A.js <==
export default "A";

==> src/components/B.js <==
export default "B";

==> src/components/index.js <==
export { default as A } from "./A";
export { default as B } from "./B";
```

And the rollup config:

```
import visualizer from "rollup-plugin-visualizer";

export default [
  {
    input: {
      index: "src/index",
      "components/index": "src/components/index",
      "components/A": "src/components/A",
      "components/B": "src/components/B"
    },
    plugins: [visualizer()],
    output: [{ dir: "dist", format: "esm" }]
  }
];
```
