### ISSUE TITLE
Network template feedback

### ISSUE THREAD

**Issue by Thrilleratplay** [btd/rollup-plugin-visualizer#61]
The network template is an excellent idea.  It displays complex interdependence with more detail.  

This is what is displayed for the project I am working on.
![module-graph](https://user-images.githubusercontent.com/553624/73097239-aa467100-3eb4-11ea-8e6c-bac1731d147d.png)

It is a little cramped.  Would the ability to zoom and adjust the force layout strength be reasonable?  It would also be nice to be able to label the nodes and highlight connecting dependents/dependencies when a node is moused over but are less critical.

**Comment by btd** [comment]
Hi, thank you for feedback. 
Actually it is first time i got it about this diagram. 
I agree about how it looks. I did not come up with a way how to compute properties of strength for d3. I would like to avoid adding ability to edit this properties for user - i believe it should just works (i already slightly manipulate chart after generation). I think i need to work on relaxing strength and think about way for zoom this chart. Currently only this one do not have any.
Also about highlight it is right idea. Will think about it

**Comment by btd** [comment]
Is it possible to get json stat file of your project? I moved implementation from d3-force to webcola for me it looks better. I would like to test your on your project.

![image](https://user-images.githubusercontent.com/334851/77229402-07496500-6b8e-11ea-816a-737aca04dfeb.png)

**Comment by Thrilleratplay** [comment]
@btd It is for an internal corporate project and due the proprietary nature of it I cannot provide something at would have module names in it.  I can see if I can obfuscate this information.

**Comment by btd** [comment]
I just published 4.0.0 as beta tag. You try it.

**Comment by Thrilleratplay** [comment]
![image](https://user-images.githubusercontent.com/553624/77327445-9fac2a80-6cf1-11ea-97e8-638d1afed47e.png)
Definite improvement.

**Comment by btd** [comment]
Great. Could you also take a look in console? It should report timing for phases.

**Comment by Thrilleratplay** [comment]
```
size scale: 0.494140625ms
nodes & links: 1.52783203125ms
constraints: 0.5498046875ms
cola: 5218.64697265625ms
```

**Comment by btd** [comment]
Thank you
