### ISSUE TITLE
Rollup 2.0.0 "isAsset" is deprecated.

### ISSUE THREAD

**Issue by minht11** [btd/rollup-plugin-visualizer#68]
While using plugin with Rollup 2.0.0 and later following warning is shown: 
Accessing "isAsset" on files in the bundle is deprecated, please use "type === 'asset'" instead.

**Comment by btd** [comment]
Thanks i dont now about this deprecation. I will fix it

**Comment by btd** [comment]
Fixed in 4.0.1
