### ISSUE TITLE
TypeError: Cannot read property 'gzip' of undefined

### ISSUE THREAD

**Issue by evdama** [btd/rollup-plugin-visualizer#69]
![Screen Shot 2020-03-30 at 21 52 21](https://user-images.githubusercontent.com/39374084/77955701-ee992780-72d0-11ea-8330-0901952b5893.png)

and that's the section where it throws
```js
  const getAvailableSizeOptions = (options) => {
    const availableSizeProperties = ["renderedLength"];
    if (options.gzip) {
      availableSizeProperties.push("gzipLength");
    }
    if (options.brotli) {
      availableSizeProperties.push("brotliLength");
    }

    return availableSizeProperties;
  };
```

as well as here
```js
    const availableSizeProperties = getAvailableSizeOptions(options);
```

**Comment by btd** [comment]
Fixed in 4.0.2

**Comment by evdama** [comment]
The `gzip` one is fixed but now there's another one
![Screen Shot 2020-03-31 at 13 10 21](https://user-images.githubusercontent.com/39374084/78020143-2a73d180-7351-11ea-8326-890902cc7237.png)

**Comment by btd** [comment]
Ok, now i need more details. Can you share your html?

**Comment by evdama** [comment]
There you go :)
https://gist.github.com/evdama/7879eddb51fd2fd938f71a59fccab616

**Comment by btd** [comment]
Fixed.

**Comment by inspire22** [comment]
Using version 5.9.0 I'm also getting this error.  It looks like it's set (to false) in const options, but I don't know why this function doesn't have acccess to it anymore.

stats.html:655 
         Uncaught TypeError: Cannot read properties of undefined (reading 'gzip')


  const getAvailableSizeOptions = (options) => {
      const availableSizeProperties = ["renderedLength"];
      if (options.gzip) {
          availableSizeProperties.push("gzipLength");
      }
      if (options.brotli) {
          availableSizeProperties.push("brotliLength");
      }
      return availableSizeProperties;
  };

**Comment by btd** [comment]
Please create new issue. I do not issue of 2020 is the same. Make sure to
post your rollup config and node version

сб, 25 февр. 2023 г., 00:09 Kevin Watt ***@***.***>:

**Comment by inspire22** [comment]
My apologies, I tested more and now it's working.  I believe the confusion of where the file ends up (stats.html in the base directory_ led me to find a stats.html that maybe I made when trying this ages ago?  I'm not sure, besides that it's working now, thanks :)
