### ISSUE TITLE
Skip rendering an index.js "block" if it's the only file in the directory.

### ISSUE THREAD

**Issue by jasonkarns** [btd/rollup-plugin-visualizer#73]
Node's file resolution allows files to be required by name or alternatively, to require a _directory_ by name which contains an index.js file [1]. For projects that are organized as a collection of directories that only contain index.js files, the visualizer is a lot "noisier" than it needs to be. The visualizer creates a block for the directory and also for the index.js file. However, in such a project, the two blocks are 1:1.

My proposal is for the visualizer to not render a block for index.js files if it is the only file in the directory. This will make the graph a lot less cluttered and easier to grok.

Example project: https://github.com/optimizely/javascript-sdk/tree/master/packages/optimizely-sdk

[1] Technically, this idea could be extrapolated to also respect node's rules for directories that have a `package.json#main` reference other than the default. However, that's quite a bit more complex because the main field can reference a file from another directory. Further, I expect it is exceedingly unlikely that a project would use package.json's in all of its subdirectories.

**Comment by btd** [comment]
Hi, 
I am semi convinced it is right thing, I will try to play with treemap UI to see how this could be improved.

**Comment by jasonkarns** [comment]
Also, thanks for the plugin. It’s been extremely useful to us for finding bits of our bundle that we can yank out.

**Comment by btd** [comment]
I have fixed this by making this default mode. If node has single child they will be merged.
