### ISSUE TITLE
Treemap - Custom colors map

### ISSUE THREAD

**Issue by raphael22** [btd/rollup-plugin-visualizer#77]
Hi there.

I have some trouble reading dependencies with some of our big projects with the actual colors map.
![image](https://user-images.githubusercontent.com/3912356/89299200-a2873680-d666-11ea-8f9d-055d0ecfb982.png)

I try to dig in the treemap/color.js script but I was a bit confused on how to override colors.

May I have some clue on this ?
Also the yellow part should not be as big as the pink part ?
Thanks

**Comment by btd** [comment]
Hi,

there is no way for now to override colors. I think plugin should work in most cases just as is. More options - more problems for future to support/maintain.
I can agree that color palette is a bit bright ( i would add some sort of pastel colors ) if you want to do something in this area i am welcome to support/review PR.
Currently rainbow coloring works such way:
https://github.com/btd/rollup-plugin-visualizer/blob/master/src/treemap/color.js#L35
1. It selects number of children (it is easier number of subroot elements in one bundle or number of bundles). 
2. It tries to map numbers to color pallet
3. It selects text color according background lightness

Current version uses this color scheme: https://github.com/d3/d3-scale-chromatic#interpolateSpectral
Basic way to fix as it looks to me need to select something less bright.

Pink part is 2.8mb and yellow only 80kb - so no they should not be the same.

**Comment by raphael22** [comment]
Thx ! I will get on this after holidays.

**Comment by btd** [comment]
I tried to make a change to use less right colors. You can see in master branch i removed using d3 color scale and used plain hsl. It looks like this:

![image](https://user-images.githubusercontent.com/334851/89626567-e6ae4d00-d899-11ea-9a2f-54a22c56d0f8.png)

If you want you can play around with coefficients if you will find better.

**Comment by btd** [comment]
I think this is ok for now. If you want you can play with saturation and light of colors, if you find better constants.

**Comment by raphael22** [comment]
Thanks ! This is fine like that.
For anyone looking to customise color you can always use sed on generated graph.html to replace hsl value.
```sed -i "s/hsl(360 * n, 0.6, 0.85)/<my-custom-hsl>/" graph.html```
