### ISSUE TITLE
Avast detects visualizer as virus 

### ISSUE THREAD

**Issue by aminya** [btd/rollup-plugin-visualizer#82]
If I ask the visualizer to open the browser by default, Avast will detect it as a virus. 
![image](https://user-images.githubusercontent.com/16418197/96407149-5b5d0c00-11a6-11eb-8e55-025dd2fc0532.png)

**Comment by btd** [comment]
I do not see from screenshot that issue is in my plugin

**Comment by aminya** [comment]
I will report this to npm anyway.

**Comment by btd** [comment]
Ok
