### ISSUE TITLE
ReferenceError: nodesData is not defined

### ISSUE THREAD

**Issue by mauroporras** [btd/rollup-plugin-visualizer#83]
I'm getting this error when I open the `stats.html` in Chrome's latest version for macOS: `ReferenceError: nodesData is not defined`.

I'll e-mail you my file. Thank you very much.

**Comment by jpicton** [comment]
Fairly certain this is caused by the latest version of the pupa dependency (2.1.0). The brace template matching has changed (see https://github.com/sindresorhus/pupa/commit/9210fdfbc7a48c652c67d215823c0279f9102315) and it appears that it no longer supports the uppercase "D" in "nodesData".

**Comment by btd** [comment]
Hi, thank you for bringing this me. I dropped pupa because it is not good to publish minor versions with breaking changes
