### ISSUE TITLE
Iframing contents does not show the full graph

### ISSUE THREAD

**Issue by seriema** [btd/rollup-plugin-visualizer#84]
Using TeamCity it's possible to use any .html file as a custom Report Tab. Using rollup-plugin-visualizer ends up not showing the full graph. As seen here:
![image](https://user-images.githubusercontent.com/693684/98010884-862a9f80-1df7-11eb-9062-f3b608c4093e.png)

As a comparison, the same scenario works fine with [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) (although a different bundle being analyzed):
![image](https://user-images.githubusercontent.com/693684/98011048-af4b3000-1df7-11eb-8f58-125777c7c9c5.png)

Stats file with full html and json:
[rollup-stats.zip](https://github.com/btd/rollup-plugin-visualizer/files/5482528/rollup-stats.zip)

**Comment by btd** [comment]
Can you copy me html for iframe and css if any attached to it? Otherwise i cannot help. Also is it possible to set attributes of iframe like width, height?

**Comment by seriema** [comment]
Setting attribute of iframe, no I don't think that's possible and it shouldn't be needed as the graph shouldn't grow bigger than it's owning container as a general rule I think.

Currently I can't share the HTML but one thing I noticed was that if I right click and select "reload iframe" it fits. So I suspect it's how rollup-plugin-visualizer is calculating it's tree-map size. Have you compared with webpack-bundle-analyzer to see what's different?

**Comment by btd** [comment]
> Have you compared with webpack-bundle-analyzer to see what's different?
No. I do not think this relavant. This completly different code and rendering is very different (svg vs canvas)

**Comment by seriema** [comment]
I can share this for now. The closest parent iframe is the same for both cases:

```
<iframe
	title="Rollup Analysis"
	class="MainUITabAdapter__iframe--2N IframeAdapter__iframe--1d"
	src="http://[redacted]/viewLog.html?tab=report_[redacted]"
	id="iFrameResizer0"
	scrolling="no"
	style="overflow: hidden; height: 724px;"
>
</iframe>
```

**Comment by btd** [comment]
Thank you, i think it is related to window resize because of component approach loading happen in teamcity. Can you try 4.2.0?

**Comment by seriema** [comment]
It works. Thank you.
![image](https://user-images.githubusercontent.com/693684/98048491-14ba1380-1e2e-11eb-96a9-42c6a3db54c3.png)
