### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by charlag** [btd/rollup-plugin-visualizer#85]
Thank you for the awesome plugin!

I would like to ask if it's possible to exclude certain modules/chunks. We have some data in small modules (like translations) which scew the graph quite a bit. Would be great if there was a callback or regex option to exclude them.

**Comment by btd** [comment]
@charlag i have started to look to this feature, may i ask some questions about your use case. How do you name staff? Is translations in separate bundle/chunks? It would be nice to take a look on how diagrams looks for you, if possible.

**Comment by charlag** [comment]
@btd hi, thanks for working on this!

This is a bit of an old diagram but translations look the same:
https://github.com/tutao/tutanota/issues/2671#issuecomment-773453794

**Comment by btd** [comment]
@charlag thanks for example. I noticed on your picture, that some chunks contains full path to files like / home / ivk .... . Do you have any ideas why this happen for some chunks and not for others?

**Comment by charlag** [comment]
@btd that's odd, I'm not sure yet. You can try to build it yourself if you like, it's as simple as `npm ci && node dist` or I can have a look sometime later

**Comment by btd** [comment]
@charlag I fixed both things, paths from your chart and added basic filtering. Just 2 regexp inputs.

**Comment by charlag** [comment]
@btd thanks a lot! Is it documented now? There are no commits/PRs linked to the issue

**Comment by btd** [comment]
@charlag it is in chart UI, i will add prefill for this a little later
