### ISSUE TITLE
Only shows "root 100%" in Safari (macOS)

### ISSUE THREAD

**Issue by akauppi** [btd/rollup-plugin-visualizer#88]
>Share with me your stats html file. It does not contain your source code - it is completely safe. You can send it to my email (see my github profile).

Safari 14.0.3 (macOS):

<img width="217" alt="safari" src="https://user-images.githubusercontent.com/1297734/111368491-a0766300-869e-11eb-9d52-53e53682a849.png">

Chrome 88.0:

<img width="217" alt="chrome" src="https://user-images.githubusercontent.com/1297734/111368637-cd2a7a80-869e-11eb-8e68-3b317eb5c89d.png">

Safari seems to render the data wrong. Maybe a CSS incompatibility - there are no errors in the browser console.

`rollup-plugin-visualizer` 4.2.0

**Comment by btd** [comment]
Fixed in 4.2.1
