### ISSUE TITLE
Text in main html is not visible

### ISSUE THREAD

**Issue by stormojm** [btd/rollup-plugin-visualizer#89]
After updating to the latest version (4.2.1), I am no longer seeing any text displayed in the stats html file.

![DispalyIssue](https://user-images.githubusercontent.com/1295150/112063565-fa13dd00-8b37-11eb-97ef-3c3a25fc49fc.png)

I built this using node 14 and rollup 2.42.2 on MacOS.  Both Firefox and Chrome have this issue, however Safari is working fine.

Downgrading back to 4.2.0 solves this issue.  I was also able to reproduce this issue with a basic/new project which only used the visualizer plugin.

**Comment by btd** [comment]
Ok. Thanks for the report will try to take a look tomorrow.

пн, 22 мар. 2021 г., 22:56 Jarrod Stormo ***@***.***>:

**Comment by btd** [comment]
Thanks for report again, fixed in 4.2.2
