### ISSUE TITLE
Doesn't work with TypeScript

### ISSUE THREAD

**Issue by Arrow7000** [btd/rollup-plugin-visualizer#9]
This doesn't seem to work when using TypeScript. It looks like it is only displaying the size of my `main.ts` file and not the entire module tree it pulls in.

In my screenshot the other - much larger - module is a file that imports a bunch of SVGs.

![2017-11-02_17-13-57](https://user-images.githubusercontent.com/13225609/32340085-7ffb5148-bff1-11e7-9214-c46eb86e3a95.png)

**Comment by btd** [comment]
Hi, sorry for very late response.

Could you please create for me very simple repo where i can play, test this? I do not use ts personally anywhere

**Comment by dgreene1** [comment]
worked for me, and I have TypeScript files. This can be closed for real.
