### ISSUE TITLE
add typescript definition

### ISSUE THREAD

**Issue by achmadk** [btd/rollup-plugin-visualizer#91]
Hello, @btd . I am using this rollup plugin in [vitejs](https://vitejs.dev/). When I want to add this plugin into vitejs config file `vite.config.ts`, I have to convert `visualizer` function from `unknown` then rollup's `Plugin` like this
```ts
plugins: [
  {
      ...((visualizer({
        gzipSize: true,
        brotliSize: true,
        open: true,
      }) as unknown) as Plugin),
      enforce: 'post',
      apply: 'build',
  }
]
```

Can I help you to add typescript definition of this plugin? When `d.ts` file has been added, you can just write like this
```ts
plugins: [
  {
      ...visualizer({
        gzipSize: true,
        brotliSize: true,
        open: true,
      }),
      enforce: 'post',
      apply: 'build',
  }
]
```

**Comment by achmadk** [comment]
If you don't mind, you can check [typescript definitions draft here](https://github.com/btd/rollup-plugin-visualizer/compare/master...achmadk:add-typescript-definition).

**Comment by btd** [comment]
Hi, thanks for the issue. I am in between stage to convert plugin to TS. I do not have any ETA now, but maybe i will release it by stages, as plugin code already converted and front end code will be next.

**Comment by BoBoooooo** [comment]
![image](https://user-images.githubusercontent.com/25972237/112959522-1803c200-9176-11eb-9c31-a7115585fdcf.png)

I'm using this(version 2.6.0) in vite too... 

but where is the gzipSize and brotliSize option ..

**Comment by btd** [comment]
@BoBoooooo i do not support anything outside of this repo, @types/rollup-plugin-visualizer also. Just wait for v5 branch to be finished.

**Comment by btd** [comment]
Just release v5, it has type declarations
