### ISSUE TITLE
Doesn't support gizp and brotli anymore?

### ISSUE THREAD

**Issue by anncwb** [btd/rollup-plugin-visualizer#94]
Share with me your stats html file. It does not contain your source code - it is completely safe. You can send it to my email (see my github profile).

If you cannot provide me stats html file, provide **all** of this:

- [ ] Provide your rollup config (this is most important, because some plugins changes paths to files)
- [ ] Provide your node and dependencies versions
- [ ] Your OS type and version
- [x] Screenshot of problem

If you do not follow template, issue will be closed without comment.

It can be seen from the screenshot of #93 . gizplength is 0

![image](https://user-images.githubusercontent.com/28132598/113272631-664bc900-930e-11eb-9f6c-e02d289fe98c.png)
![image](https://user-images.githubusercontent.com/28132598/113272652-6ba91380-930e-11eb-8dac-de9683c3f0c6.png)

**Comment by btd** [comment]
It is in changelog. brotli and gzip now works only for rollup >= 2.44. Just type npm/yarn update, with very high probability it will autofixed.
