### ISSUE TITLE
Object.fromEntries error

### ISSUE THREAD

**Issue by anncwb** [btd/rollup-plugin-visualizer#97]
After upgrading to 5.3.3, an error is reported, Object.fromEntries does not exist, and 5.3.0 is normal

**Comment by btd** [comment]
Browser or nodejs. Which version?

**Comment by BoBoooooo** [comment]
the same question  in 5.3.3 version.

![image](https://user-images.githubusercontent.com/25972237/114350724-2dc4ae80-9b9c-11eb-94b9-3632bb1306c8.png)

**Comment by anncwb** [comment]
node14

**Comment by btd** [comment]
I published 5.3.4. Please next time reporting issues, follow template. I will close it without answering next time.
