### ISSUE TITLE
Add fileSize option

### ISSUE THREAD

**Issue by marcofugaro** [btd/rollup-plugin-visualizer#98]
Related: https://github.com/btd/rollup-plugin-visualizer/issues/96#issuecomment-819727120

In my case, the library I'm using this plugin on gets tree-shaken, so the displayed filesizes don't match.

I would like an option to remove them completely **both from the visualization and from the tooltip**, since they may be confusing. Ideally only percentages would be displayed.

The option would be something like:

`fileSize` (boolean, default `true`) - Collect file size from source code and display it in the chart.

**Comment by btd** [comment]
I just published 5.4.0 where i changed UI of treemap a bit. I added notice to tooltip about what is a size and remove size from text labels of nodes.

**Comment by marcofugaro** [comment]
Thanks!

However I see in the new version that the names increase in font-size to fill all the available space.

This may often be confusing, since shorter names will appear bigger, even if the treemap block is smaller.

It also confusingly creates a Word Cloud visualization effect with the names, which influences the perception of the sizes.
Could you do an option to disable this?

![image](https://user-images.githubusercontent.com/7217420/115226369-738af500-a10f-11eb-8e19-a31679363ba8.png)

**Comment by btd** [comment]
Yep that seems true. My main idea was to reduce sizes to make sure it tries to fit the box instead of being cut on edge.

I do not want to make and support tons of options, my preference is to have reasonable opinionated defaults.

**Comment by btd** [comment]
Updated to 5.4.1 it will center labels, but without font grow.
